#!/usr/bin/env bash
#
# File: developer_setup/githooks/pre-push
#
echo "Before pushing, running tests"

# Ensure the branch name is correct
echo -n "1. Checking that branch naming is correct..."
name=$(git symbolic-ref --short HEAD)
echo $name | grep -E '^main$|^develop$|^hotfix/|^feature/|^bugfix/|^doc/'
if [ $? -ne 0 ]; then
    echo "'$name' is not an acceptable branch name"
    exit 1
fi
echo "branch name $name is ok."

echo "2. Unit tests"
poetry run make coverage || exit 2

echo "3. pylint, pydocstyle, black (diff)"
poetry run make lint || exit 3

echo "4. Version Tracking"
poetry run make version_control  # This does not need to fail, just needs a warning.

echo "Cleanliness checked. This does not include functional tests." 
